[book]
authors = ["MarcusWentz"]
language = "en"
multilingual = false
src = "src"
title = "🎨 fluent 🎨"

[output.html]
git-repository-url = "https://github.com/MarcusWentz/fluent-mdbook-test"
edit-url-template =  "https://github.com/MarcusWentz/fluent-mdbook-test/edit/main/src/README.md"
additional-js =  ["src/static/solidity.min.js"]